name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Neovim
        run: |
          mkdir -p build
          wget https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage
          chmod +x nvim.appimage
          mv nvim.appimage ./build/nvim
          echo "${PWD}/build" >> $GITHUB_PATH

      - name: Download RipGrep
        run: |
          mkdir -p build
          wget https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
          tar xfz ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
          mv ripgrep-13.0.0-x86_64-unknown-linux-musl/rg ./build/rg

      - name: deps
        run: make deps

      - name: test
        run: make test

      - name: tarball
        run: |
          TAG=$(git name-rev --tags --name-only ${{github.ref}})
          TARBALL="nvim-client-proxy-${TAG}.tar.gz"
          echo TAG=${TAG} >> $GITHUB_ENV
          echo TARBALL=${TARBALL} >> $GITHUB_ENV
          tar --create -z --file ${TARBALL} *.md LICENSE src test *.rockspec

      - name: Release Notes
        run: make Release.txt

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.TARBALL}}
          body_path: Release.txt

      - name: LuaRocks Release
        run: |
          ./.deps/usr/bin/luarocks pack nvim-client-proxy
          ./.deps/usr/bin/luarocks upload *.rockspec --api-key=${{ secrets.LUAROCKS_KEY }}

